// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh_F26cn9E7H5e46AUsXlsEzH52D-CFU8',
    appId: '1:67529950435:web:6ec697fdc582df78d1b1d6',
    messagingSenderId: '67529950435',
    projectId: 'chatapp1-bf710',
    authDomain: 'chatapp1-bf710.firebaseapp.com',
    storageBucket: 'chatapp1-bf710.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlX919moerMchKugF3UAihJX7pHaD14vI',
    appId: '1:67529950435:android:bb0692e7cbc47907d1b1d6',
    messagingSenderId: '67529950435',
    projectId: 'chatapp1-bf710',
    storageBucket: 'chatapp1-bf710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpBvmKpTgB_lyp-YU5SPc2ez_4Kr1sSlA',
    appId: '1:67529950435:ios:090510114981cf83d1b1d6',
    messagingSenderId: '67529950435',
    projectId: 'chatapp1-bf710',
    storageBucket: 'chatapp1-bf710.appspot.com',
    iosBundleId: 'com.example.chatAppMain',
  );
}
